on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install packages
        run: sudo apt-get install -y ttfautohint fontforge python2 python2-pip-whl

      - name: Install python packages
        run: |
          python2 /usr/share/python-wheels/pip-20.3.4-py2.py3-none-any.whl/pip install --no-index /usr/share/python-wheels/pip-20.3.4-py2.py3-none-any.whl
          python2 -m pip install fonttools
          python3 -m pip install ttfautohint-py

      - uses: actions/checkout@v3

      - name: Build
        run: ./make.sh

      - name: Make directories for upload-artifact
        run: |
          mkdir UDEAWN_${{ github.ref_name }}
          mv build/UDEAWN-* UDEAWN_${{ github.ref_name }}

      - uses: actions/upload-artifact@v3
        with:
          name: UDEAWN_${{ github.ref_name }}
          path: UDEAWN_${{ github.ref_name }}
