on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install packages
        run: sudo apt-get install -y ttfautohint fontforge python2

      - name: Install python packages
        run: |
          sudo python2 -m pip install fonttools
          sudo python3 -m pip install ttfautohint-py

      - uses: actions/checkout@v3

      - name: Build
        run: ./make.sh

      - name: Make directories for upload-artifact
        run: |
          mkdir UDEAWN_${{ github.ref_name }}
          mv build/UDEAWN-* UDEAWN_${{ github.ref_name }}

      - uses: actions/upload-artifact@v3
        with:
          name: UDEAWN_${{ github.ref_name }}
          path: UDEAWN_${{ github.ref_name }}
