on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install packages
        run: sudo apt-get install -y ttfautohint fontforge python2 python2-pip-whl

      - name: Install python packages
        run: |
          python2 /usr/share/python-wheels/pip-20.3.4-py2.py3-none-any.whl/pip install --no-index /usr/share/python-wheels/pip-20.3.4-py2.py3-none-any.whl
          python2 -m pip install fonttools
          python3 -m pip install ttfautohint-py

      - uses: actions/checkout@v3

      - name: Build
        run: |
          ./make-n.sh
          ./make-s.sh
          ./make.sh

      - name: Make directories for upload-artifact
        run: |
          mkdir UDEAWNi_${{ github.ref_name }}
          mv build/UDEAWNi-* UDEAWNi_${{ github.ref_name }}
          cp source/LICENSE_BIZUDGothic UDEAWNi_${{ github.ref_name }}
          cp source/LICENSE_Illusion UDEAWNi_${{ github.ref_name }}
          cp source/NotoEmoji/OFL.txt UDEAWNi_${{ github.ref_name }}/LICENSE_NotoEmoji
          cp LICENSE_UDEAWNi UDEAWNi_${{ github.ref_name }}
      - run: |
          mkdir UDEAWNn_${{ github.ref_name }}
          mv build/UDEAWNn-* UDEAWNn_${{ github.ref_name }}
          cp source/LICENSE_BIZUDGothic UDEAWNn_${{ github.ref_name }}
          cp source/NotoEmoji/OFL.txt UDEAWNn_${{ github.ref_name }}/LICENSE_NotoEmoji
          cp LICENSE_UDEAWNn UDEAWNn_${{ github.ref_name }}
      - run: |
          mkdir UDEAWNs_${{ github.ref_name }}
          mv build/UDEAWNs-* UDEAWNs_${{ github.ref_name }}
          cp source/LICENSE_BIZUDGothic UDEAWNs_${{ github.ref_name }}
          cp source/NotoEmoji/OFL.txt UDEAWNs_${{ github.ref_name }}/LICENSE_NotoEmoji
          cp LICENSE_UDEAWNs UDEAWNs_${{ github.ref_name }}

      - uses: actions/upload-artifact@v3
        with:
          name: UDEAWNi_${{ github.ref_name }}
          path: UDEAWNi_${{ github.ref_name }}

      - uses: actions/upload-artifact@v3
        with:
          name: UDEAWNn_${{ github.ref_name }}
          path: UDEAWNn_${{ github.ref_name }}

      - uses: actions/upload-artifact@v3
        with:
          name: UDEAWNs_${{ github.ref_name }}
          path: UDEAWNs_${{ github.ref_name }}
